Abort Actions fix - CASMHMS-4755
Cray-HPE/hms-firmware-action pull request #71
Opened 2022-03-22 13:41 UTC by mbuchmann-hpe

### Summary and Scope

If an action is aborted (an API call), and the action is currently being processed by the update
loop, the aborted state is overwritten and the action is not aborted.
Added a check to store action to see if the action was aborted and adjust the state if it was.

Updated calls to avoid direct calling to storage layer, instead created local functions in domain layer.

DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N

REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? 1.20.0

REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: (C) Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? Y

### Issues and Related PRs

CASMHMS-4755
CASMHMS-5493

### Testing

Tested locally
Ran unit tests and ct tests

Were the install/upgrade based validation checks/tests run? N
Were continuous integration tests run? Y
Was an Upgrade tested?                 N
Was a Downgrade tested?              N
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? NA

### Risks and Mitigations

This appears to be a low risk change

Requires:

NA

2022-03-22 13:51 UTC, mpkelly-hpe approved these changes

2022-03-22 18:25 UTC, nieuwsma requested changes
we should try to find a different way to do this.

2022-09-08 20:49 UTC, nieuwsma approved these changes

2022-09-08 21:49 UTC, schooler-hpe approved these changes

2022-09-08 21:50 UTC, merged